spring:
  application:
    name: SpringBootGraphQL
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  graphql:
    schema:
      locations: classpath:graphql/

server:
  port: 8081
#  max-http-header-size: 16384